# Generated by Django 6.0.2 on 2026-05-25 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('OD', 'Odisha'), ('TN', 'TamilNadu'), ('GA', 'Goa'), ('HR', 'Haryana')], max_length=2)),
            ],
        ),
    ]
