# Generated by Django 6.0.2 on 2026-05-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
